/**
 * Flock Journal - durable workflow event journal
 *
 * Registers the `flock_event` tool, which appends one validated JSON event
 * per line to `<cwd>/.flock/events.jsonl` (append-only JSON Lines; the
 * directory is created if missing). The `.flock/` directory is gitignored
 * and never committed, the same convention as handoff files.
 *
 * Event schema (v1, additive-only evolution):
 *   {v: 1, ts, run_id, workflow, event, repo, issue?, pr?, branch?, data? {}}
 *
 * - `ts` is an ISO-8601 timestamp generated by the tool, never by the caller.
 * - Emission is supervisor-only: nested Herdr workers never write journal
 *   events; their worktrees are removed after merge.
 *
 * Fail-open contract: missing required fields or unknown event names are
 * rejected with a clear tool error so callers learn immediately, but a
 * filesystem write failure only returns a warning in the tool result and
 * never throws or fails the caller's run.
 */

import { appendFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { StringEnum } from "@earendil-works/pi-ai";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

export const JOURNAL_SCHEMA_VERSION = 1;
export const JOURNAL_DIR_NAME = ".flock";
export const JOURNAL_FILE_NAME = "events.jsonl";

export const FLOCK_EVENT_NAMES = [
	"run_started",
	"issue_dispatched",
	"pr_opened",
	"gate_result",
	"review_verdict",
	"rework_dispatched",
	"run_stopped",
	"merge_verified",
	"issue_closed",
	"worktree_cleaned",
] as const;

export type FlockEventName = (typeof FLOCK_EVENT_NAMES)[number];

/** Raw caller input; every field is validated before use. */
export interface FlockEventParams {
	run_id?: unknown;
	workflow?: unknown;
	event?: unknown;
	repo?: unknown;
	issue?: unknown;
	pr?: unknown;
	branch?: unknown;
	data?: unknown;
}

export interface ValidatedEventParams {
	run_id: string;
	workflow: string;
	event: FlockEventName;
	repo: string;
	issue?: number;
	pr?: number;
	branch?: string;
	data?: Record<string, unknown>;
}

export interface FlockJournalEvent {
	v: number;
	ts: string;
	run_id: string;
	workflow: string;
	event: FlockEventName;
	repo: string;
	issue?: number;
	pr?: number;
	branch?: string;
	data?: Record<string, unknown>;
}

export type ValidationResult = { ok: true; params: ValidatedEventParams } | { ok: false; error: string };

export type AppendResult =
	| { ok: true; path: string }
	| { ok: false; path: string; warning: string };

export function journalPathFor(cwd: string): string {
	return join(cwd, JOURNAL_DIR_NAME, JOURNAL_FILE_NAME);
}

function isNonEmptyString(value: unknown): value is string {
	return typeof value === "string" && value.trim().length > 0;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Validate caller-supplied parameters. Required fields must be non-empty
 * strings; `event` must be one of FLOCK_EVENT_NAMES. Optional fields are
 * type-checked when present.
 */
export function validateEventParams(input: FlockEventParams): ValidationResult {
	for (const field of ["run_id", "workflow", "repo"] as const) {
		if (!isNonEmptyString(input[field])) {
			return { ok: false, error: `missing or invalid required field "${field}": expected a non-empty string` };
		}
	}
	if (!isNonEmptyString(input.event)) {
		return { ok: false, error: `missing or invalid required field "event": expected one of ${FLOCK_EVENT_NAMES.join(", ")}` };
	}
	if (!(FLOCK_EVENT_NAMES as readonly string[]).includes(input.event)) {
		return {
			ok: false,
			error: `unknown event "${input.event}": expected one of ${FLOCK_EVENT_NAMES.join(", ")}`,
		};
	}
	for (const field of ["issue", "pr"] as const) {
		const value = input[field];
		if (value !== undefined && !(typeof value === "number" && Number.isInteger(value) && value > 0)) {
			return { ok: false, error: `invalid optional field "${field}": expected a positive integer` };
		}
	}
	if (input.branch !== undefined && !isNonEmptyString(input.branch)) {
		return { ok: false, error: `invalid optional field "branch": expected a non-empty string` };
	}
	if (input.data !== undefined && !isPlainObject(input.data)) {
		return { ok: false, error: `invalid optional field "data": expected an object` };
	}
	return {
		ok: true,
		params: {
			run_id: input.run_id as string,
			workflow: input.workflow as string,
			event: input.event as FlockEventName,
			repo: input.repo as string,
			issue: input.issue as number | undefined,
			pr: input.pr as number | undefined,
			branch: input.branch as string | undefined,
			data: input.data as Record<string, unknown> | undefined,
		},
	};
}

/** Build the stored event. `ts` is generated here, never supplied by the caller. */
export function buildJournalEvent(params: ValidatedEventParams, ts: string = new Date().toISOString()): FlockJournalEvent {
	const event: FlockJournalEvent = {
		v: JOURNAL_SCHEMA_VERSION,
		ts,
		run_id: params.run_id,
		workflow: params.workflow,
		event: params.event,
		repo: params.repo,
	};
	if (params.issue !== undefined) event.issue = params.issue;
	if (params.pr !== undefined) event.pr = params.pr;
	if (params.branch !== undefined) event.branch = params.branch;
	if (params.data !== undefined) event.data = params.data;
	return event;
}

/**
 * Append one event line to the journal, creating `.flock/` if needed.
 * Fail-open: a write failure returns a warning instead of throwing.
 */
export function appendJournalEvent(cwd: string, event: FlockJournalEvent): AppendResult {
	const journalPath = journalPathFor(cwd);
	try {
		mkdirSync(dirname(journalPath), { recursive: true });
		appendFileSync(journalPath, `${JSON.stringify(event)}\n`, "utf8");
		return { ok: true, path: journalPath };
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		return {
			ok: false,
			path: journalPath,
			warning: `flock_event could not write the journal at ${journalPath}: ${message}. Event not recorded; the run continues unchanged (fail-open).`,
		};
	}
}

const FlockEventSchema = Type.Object({
	run_id: Type.String({ description: "Identifier for one operator run or worker session" }),
	workflow: Type.String({ description: 'Workflow name, e.g. "operator-run" or "github-issue-worker"' }),
	event: StringEnum(FLOCK_EVENT_NAMES, { description: "Journal event name" }),
	repo: Type.String({ description: "owner/repo or absolute repository path" }),
	issue: Type.Optional(Type.Number({ description: "Issue number" })),
	pr: Type.Optional(Type.Number({ description: "Pull request number" })),
	branch: Type.Optional(Type.String({ description: "Branch name" })),
	data: Type.Optional(
		Type.Record(Type.String(), Type.Any(), {
			description:
				'Optional structured payload, e.g. {passed: true} for gate_result, {verdict: "clean"|"blocking"} for review_verdict, {reason: "<verbatim stop reason>"} for run_stopped, or pane/workspace/worktree IDs for issue_dispatched',
		}),
	),
});

export default function (pi: ExtensionAPI) {
	pi.registerTool({
		name: "flock_event",
		label: "Flock Event",
		description: [
			"Append one workflow status event to the Flock journal at <cwd>/.flock/events.jsonl (append-only JSON Lines, schema v1; the directory is created if needed and never committed).",
			`The stored event is {v: 1, ts, run_id, workflow, event, repo, issue?, pr?, branch?, data?}; ts is generated by this tool, not the caller. Known events: ${FLOCK_EVENT_NAMES.join(", ")}.`,
			"Missing required fields or unknown event names are rejected with an error. A journal write failure only returns a warning and never fails the run: warn and continue.",
			"Supervisor-only: nested Herdr workers never call this tool.",
		].join(" "),
		parameters: FlockEventSchema,

		async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
			const validation = validateEventParams(params);
			if (!validation.ok) {
				return {
					content: [{ type: "text", text: `flock_event rejected: ${validation.error}` }],
					details: undefined,
					isError: true,
				};
			}

			const event = buildJournalEvent(validation.params);
			const result = appendJournalEvent(ctx.cwd, event);
			if (!result.ok) {
				return {
					content: [{ type: "text", text: `Warning: ${result.warning}` }],
					details: { path: result.path, event, written: false, warning: result.warning },
				};
			}
			return {
				content: [
					{
						type: "text",
						text: `Journal event recorded: ${event.event} (workflow ${event.workflow}, run ${event.run_id}) in ${result.path}`,
					},
				],
				details: { path: result.path, event, written: true },
			};
		},
	});
}
